name: flutter_boilerplate
description: Flutter Boilerplate by Michael Frischbutter inspired by
  https://github.com/SimpleBoilerplates/Flutter/

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  connectivity_plus: ^2.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.3
  flutter_riverpod: ^1.0.0-dev.7
  flutter_secure_storage: ^5.0.2
  hooks_riverpod: ^1.0.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  pretty_dio_logger: ^1.1.1
  sentry: ^6.5.1
  shared_preferences: ^2.0.8

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: null
  dart_code_metrics: ^4.4.0
  dependency_validator: ^3.1.0
  flutter_gen_runner: null
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  import_sorter: ^4.6.0
  json_serializable: null
  logger: null
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0
  very_good_performance: ^0.0.4

flutter:
  uses-material-design: true

  assets:
    - 'assets/translation/'
    - 'assets/env/'
